# Autogenerated wrapper script for rure_jll for aarch64-apple-darwin
export librure

JLLWrappers.@generate_wrapper_header("rure")
JLLWrappers.@declare_library_product(librure, "@rpath/librure.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        librure,
        "lib/librure.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
